/* inline functions fo sparse tensor */
namespace apex_tensor{

	APEX_ADD_SUPPORT_ALLOC_LIKE_OP( CSTensor1D );
	APEX_ADD_SUPPORT_ALLOC_LIKE_OP( CSTensor2D );

	APEX_ADD_SUPPORT_SAMPLE_BINARY_OP( CSTensor1D );
	APEX_ADD_SUPPORT_SAMPLE_BINARY_OP( CSTensor2D );

	APEX_ADD_SUPPORT_ADD_OP( CSTensor1D );
	APEX_ADD_SUPPORT_ADD_OP( CSTensor2D );

	APEX_ADD_SUPPORT_MUL_OP( CSTensor1D );
	APEX_ADD_SUPPORT_MUL_OP( CSTensor2D );

	APEX_ADD_SUPPORT_CLONE_OP( CSTensor1D );
	APEX_ADD_SUPPORT_CLONE_OP( CSTensor2D );
	
	APEX_ADD_SUPPORT_SCALE_OP( CSTensor2D, TENSOR_FLOAT ); 
};
